spring:
  application:
    name: sky
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      package-to-scan: com.sgugo.skyserver
knife4j:
  enable: true
  basic:
    enable: true
    username: victor
    password: victor
  setting:
    enable-footer-custom: true
    footer-custom-content: "cybor| [Victor](https://gitee.com/xiaoym/knife4j)"

    swagger-model-name: "POJO"

    enable-home-custom: false
    home-custom-location: classpath:markdown/home.md
    enable-debug: true
  documents:
    - group: 'default'
      name: 项目说明
      locations: classpath:markdown/*

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd} %-5level [%t] %c{1.}.%M(%L): %msg%n"















